Add support for SecretTypeTLS secrets
StratoAG/etcd-operator pull request #2
Opened 2020-01-10 07:52 UTC by schegi

Kubernetes knows specific TLS secrets (SecretTypeTLS). This kind of
secrets has specifically named fields (tls.crt, tls.key, ca.crt)
different from those supported by the etcd-operator. Such secretes
are e.g. generated by the cert-manager. This change adds support for
such secrets.

Please read https://github.com/coreos/etcd-operator/blob/master/CONTRIBUTING.md#contribution-flow

2020-01-10 12:19 UTC, schegi commented
Wait pls still something missing

2020-01-13 12:07 UTC, avorima requested changes
Looks good, just a few small remarks

2020-01-13 12:07 UTC, avorima commented on pkg/util/k8sutil/k8sutil.go
> +	isTLSSecret := false
Why don't you just assign this to `secret.Type == v1.SecretTypeTLS`?

2020-01-13 12:07 UTC, avorima commented on pkg/cluster/cluster.go
> +	c.logger.Info("Creating pod")
Is this really needed here?

2020-01-13 12:07 UTC, avorima commented on pkg/util/k8sutil/k8sutil.go
> +	isTLSSecret := false
I guess here is the wrong place, but adjust it around line 343.

2020-01-13 12:07 UTC, avorima commented on pkg/util/k8sutil/tls.go
> +	v1 "k8s.io/api/core/v1"
Small nit: I'm pretty sure this isn't aligned correctly. Check out the ordering around line 21

2020-01-13 14:31 UTC, merged